theme: jekyll-theme-minimal
title: "Faruk — Embedded Portfolio"
description: "ESP32 • RTOS • IoT • ROS2 • Edge AI • FPGA"
theme: jekyll-theme-minimal
logo: /assets/img/avatar.png
show_downloads: false
